// ActionTypes for Contribution Reducer
export const SELECT_WITH_BUTTON = "SELECT_WITH_BUTTON";
export const SELECTED_BY_USER = "SELECT_BY_USER";

export const CONTRIBUTE_WWHOLE_ORG = "CONTRIBUTE_WHOLE_ORG";
export const CONTRIBUTE_SPECIFIC_SHELTER = "CONTRIBUTE_SPECIFIC_SHELTER";
export const SET_SHELTER = "SET_SHELTER";

export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_SURNAME = "UPDATE_SURNAME";
export const UPDATE_EMAIL= "UPDATE_EMAIL";
export const UPDATE_PHONE_INPUT = "UPDATE_PHONE_INPUT";

// ActionTypes for Fetching Shelters from API
export const FETCH_SHELTERS_START = "FETCH_SHELTERS_START";
export const FETCH_SHELTERS_SUCCESS = "FETCH_SHELTERS_SUCCESS";
export const FETCH_SHELTERS_FAILED = "FETCH_SHELTERS_FAILED";
